spring.application.name=attendance-backend
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3308/attendance_system
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=4qhq8L6M0a1E7N3jB/gE7P1R3fS6H9yK2L5M8N0P1Q4=
jwt.expiration=86400000
